version: '3'

services:
  url_shortner:
    depends_on:
      - db
    build: .
    links:
            - "db:dbos" 
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_USER: root
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydatabase
    volumes:
      - mydbstorage:/var/lib/mysql


volumes:
  mydbstorage: {}
